version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://finance_user:finance_pass@db:5432/finance_tracker
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
    profiles:
      - backend
      - full

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    profiles:
      - frontend
      - full

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=finance_tracker
      - POSTGRES_USER=finance_user
      - POSTGRES_PASSWORD=finance_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finance_user -d finance_tracker"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    profiles:
      - db
      - backend
      - full

volumes:
  postgres_data: